# Generated by Django 5.2.9 on 2025-12-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Shopping', 'Shopping'), ('Rent', 'Rent'), ('Others', 'Others')], max_length=100),
        ),
    ]
